import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    slug: "silicone-sink-splash-guard",
    name: "Silicone Sink Splash Guard",
    price: 24,
    category: "Kitchen",
    badge: "Bestseller",
    problemSolved: "Eliminates water splash around the sink area",
    description: "Stops water splash before it reaches your wall or countertop.",
    longDescription:
      "Our food-grade silicone splash guard fits snugly around any standard faucet base. It redirects water back into the sink, keeping your countertop and wall dry after every wash. Installs in seconds with no tools and no adhesive. Dishwasher safe and heat resistant up to 230°C. Available in white, stone, and charcoal to match any kitchen.",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 312,
    inStock: true,
    featured: true,
    tags: ["sink", "splash", "kitchen", "silicone", "waterproof"],
    material: "Food-grade silicone",
    dimensions: "Fits faucet bases Ø 18–36mm",
  },
  {
    id: "2",
    slug: "bamboo-drawer-organizer-set",
    name: "Bamboo Drawer Organizer Set",
    price: 38,
    category: "Kitchen",
    problemSolved: "Ends the chaos of cluttered kitchen and bathroom drawers",
    description: "6-piece expandable bamboo set that turns any drawer into a tidy workspace.",
    longDescription:
      "This 6-piece bamboo organizer set includes two expandable dividers and four fixed-size trays. Each piece is made from sustainably harvested natural bamboo with smooth-sanded edges. The set fits most standard kitchen and bathroom drawers and can be configured dozens of ways. No tools, no adhesive, no damage to drawers.",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
      "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 187,
    inStock: true,
    featured: true,
    tags: ["drawer", "organizer", "bamboo", "kitchen", "eco"],
    material: "Sustainably harvested natural bamboo",
    dimensions: "Expandable dividers: 25–50cm width",
  },
  {
    id: "3",
    slug: "adjustable-shower-caddy",
    name: "Adjustable Shower Caddy",
    price: 34,
    originalPrice: 49,
    category: "Bathroom",
    badge: "New",
    problemSolved: "Clears shampoo bottles off the shower floor without drilling",
    description: "No-drill tension pole caddy with three adjustable shelves.",
    longDescription:
      "Install in under 3 minutes — no drilling, no screws, no wall damage. The tension pole extends from floor to ceiling and supports up to 15kg across three fully adjustable shelves. Made from 304-grade stainless steel with a rust-proof coating. Includes razor and loofah hooks on every shelf. Fits ceilings from 180cm to 280cm.",
    images: [
      "https://images.unsplash.com/photo-1552168324-d612d77725e3?w=800&q=80",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 428,
    inStock: true,
    featured: true,
    tags: ["shower", "caddy", "bathroom", "storage", "no-drill"],
    material: "304-grade stainless steel, ABS joints",
    dimensions: "Extends 180–280cm, shelves Ø 26cm",
  },
  {
    id: "4",
    slug: "magnetic-knife-utensil-strip",
    name: "Magnetic Knife & Utensil Strip",
    price: 42,
    category: "Kitchen",
    problemSolved: "Frees counter space occupied by a bulky knife block",
    description: "45cm acacia wood strip with powerful neodymium magnets.",
    longDescription:
      "Our 45cm magnetic strip mounts to any wall in minutes using the included hardware. Strong neodymium magnets hold up to 12 knives or metal utensils securely without scratching blades. The solid acacia wood backing is food-safe, naturally antibacterial, and looks beautiful in any kitchen aesthetic. Works with carbon steel and stainless steel.",
    images: [
      "https://images.unsplash.com/photo-1556909172-8c2f041fca1e?w=800&q=80",
      "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    featured: true,
    tags: ["knife", "magnetic", "kitchen", "wall mount", "organization"],
    material: "Acacia wood, neodymium magnets",
    dimensions: "45cm × 6cm × 2cm",
  },
  {
    id: "5",
    slug: "under-sink-pull-out-rack",
    name: "Under-Sink Pull-Out Rack",
    price: 58,
    originalPrice: 75,
    category: "Kitchen",
    badge: "Editor's Pick",
    problemSolved: "Turns a chaotic under-sink cabinet into organized, reachable storage",
    description: "Double-tier sliding rack that makes full use of your under-sink cabinet.",
    longDescription:
      "The under-sink area is prime real estate wasted in most homes. Our double-tier pull-out rack installs in under 10 minutes using the included hardware. Full-extension smooth-glide rails let you reach items at the very back. Holds cleaning products, brushes, and bottles up to 40cm tall. Adjustable dividers let you customize each tier for your exact products.",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    featured: true,
    tags: ["under sink", "cabinet", "kitchen", "sliding rack", "organization"],
    material: "Powder-coated steel, chrome rails",
    dimensions: "50cm × 30cm × 35cm (adjustable width)",
  },
  {
    id: "6",
    slug: "rotating-pantry-organizer",
    name: "360° Rotating Pantry Organizer",
    price: 29,
    originalPrice: 39,
    category: "Kitchen",
    problemSolved: "Stops items getting lost behind other things on pantry and cabinet shelves",
    description: "Two-tier lazy susan that brings everything to the front with a single spin.",
    longDescription:
      "How many times have you bought something only to find you already had one hidden at the back? Our two-tier 360° turntable puts everything on display. Use it in pantry cabinets, refrigerators, or bathroom medicine cupboards. The smooth ball-bearing base spins quietly and holds up to 8kg. A non-slip coating on the base keeps it anchored on any shelf.",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80",
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 341,
    inStock: true,
    featured: true,
    tags: ["lazy susan", "turntable", "pantry", "kitchen", "bathroom", "rotating"],
    material: "BPA-free ABS, steel ball bearing",
    dimensions: "Ø 25cm per tier, 23cm total height",
  },
  {
    id: "7",
    slug: "bamboo-bathroom-shelf-tower",
    name: "Bamboo Bathroom Shelf Tower",
    price: 72,
    category: "Bathroom",
    problemSolved: "Creates bathroom storage in small spaces with no drilling or wall damage",
    description: "Free-standing 4-shelf bamboo tower — fits over any standard toilet.",
    longDescription:
      "Specifically designed to reclaim the dead space above your toilet or beside your sink. Four spacious shelves hold towels, toiletries, and bathroom essentials. Made from premium carbonized bamboo with a water-resistant lacquer coating. Assembly takes under 15 minutes with the included allen key. Requires no wall fixings — simply stands in place.",
    images: [
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80",
      "https://images.unsplash.com/photo-1552168324-d612d77725e3?w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 94,
    inStock: true,
    featured: false,
    tags: ["bathroom", "shelf", "bamboo", "storage", "over toilet", "free-standing"],
    material: "Carbonized bamboo, water-resistant lacquer",
    dimensions: "60cm × 28cm × 168cm",
  },
  {
    id: "8",
    slug: "foldable-storage-cube-set",
    name: "Foldable Storage Cube Set (4-pack)",
    price: 48,
    category: "Storage",
    problemSolved: "Tames cluttered wardrobes and shelves with neat, stackable storage",
    description: "4 collapsible fabric cubes with label windows — stack, fold, store.",
    longDescription:
      "Each cube collapses flat in seconds when not in use and pops open firmly for everyday use. A rigid wire frame keeps each cube's shape under load. Reinforced top handles make moving them effortless. Clear label windows on the front let you identify contents without opening the cube. Works on wardrobe shelves, under beds, in bookcases, or on open storage units.",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80",
      "https://images.unsplash.com/photo-1558618047-f3d1fed16e76?w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 267,
    inStock: false,
    featured: false,
    tags: ["storage", "cubes", "closet", "foldable", "wardrobe", "organization"],
    material: "Non-woven polypropylene, steel wire frame",
    dimensions: "30cm × 30cm × 30cm per cube",
  },
];

export const getProductBySlug = (slug: string) =>
  products.find((p) => p.slug === slug);

export const getFeaturedProducts = () => products.filter((p) => p.featured);

export const getProductsByCategory = (category: string) =>
  category === "All" ? products : products.filter((p) => p.category === category);
